--- # modulo AT
- hosts: apacheweb
  remote_user: ansible
  become: yes
  become_method: sudo
  gather_facts: no
  tasks:
  - name: Programando algo con AT
    at: command="ls -al /var/log > /home/ansible/at.log" count=1 units="minutes" 
# se le indica al at con count el tiempo en concreto y con units que tipo de unidad se refiere la anterior, en este ejemplo es un minuto desde ahora
  #- name: Programando algo con AT
  #  at: command="ls -al /var/log > /home/ansible/at.log" state=absent
  #  en caso que se desee borrar la tarea anterior
