--- # Modulo Jinja, crear fichero con contenido dinamico
- hosts: apacheweb:aptserver
  remote_user: ansible
  become: yes
  become_method: sudo
  gather_facts: yes
  vars:
   userName: test
   userPassword: password123
   connectionType: ssh 
  tasks:
  - name: Instalarel fichero de configuracion customizado para el sistema
    template: src=test.conf.j2 dest=/home/ansible/test.conf owner=ansible group=ansible mode=750
