- hosts: '{{ myhosts }}'
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: '{{ gather }}'
  vars:
    myhosts: centos
    gather: yes
    pkg: httpd
  tasks:
  - name: Instalar el paquete indicado
    yum:
      name: '{{ pkg }}'
      state: removed
