--- # Modulo Service
- hosts: apacheweb
  remote_user: ansible
  become: yes
  become_method: sudo
  gather_facts: no
  tasks:
  - name: Instalar servicio web
    yum: name=httpd state=latest
  - name: Iniciar servicio web
    service: name=httpd state=started
  - name: habilitar servicio
    service: name=httpd enabled=yes
