--- # LOOP PLAYBOOK EXAMPLE
- hosts: apacheweb
  remote_user: ansible
  become: yes
  become_method: sudo
  gather_facts: no
  tasks: 
    - name: Add lista de usuarios
      user: name={{ item }} state=present
      with_items:
        - user1
        - user2
        - user3

