--- # probando J2 module de plantilla
- hosts: apacheweb,aptserver
  remote_user: ansible
  become: yes
  become_method: sudo
  gather_facts: yes
  vars:
    userName: ansible
    userPassword: $$m4mb0??
    connectionType: SFTP
  tasks:
    - name: Instalar archivo de configuracion customizado para el systema
      template: src=test.conf.j2 dest=/home/ansible/test.conf owner=ansible group=ansible mode=750 
